name: multi_window_linux
description: The Linux implementation for the multi_window plugin.
version: 0.1.1
repository: https://gitlab.com/wolfenrain/multi_window
issue_tracker: https://gitlab.com/wolfenrain/multi_window/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  multi_window_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: MultiWindowLinuxPlugin
