name: multi_window
description: A package for adding multi window support to Flutter on Desktop.
version: 0.2.0
repository: https://gitlab.com/wolfenrain/multi_window
issue_tracker: https://gitlab.com/wolfenrain/multi_window/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  multi_window_interface: ^0.2.0
  multi_window_linux: ^0.2.0
  multi_window_macos: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        default_package: multi_window_linux
      macos:
        default_package: multi_window_macos
